name: Build Wheels and Publish

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'pyfastcdc/**'
      - 'pyproject.toml'
      - 'MANIFEST.in'
  pull_request:
  workflow_dispatch:
    inputs:
      publish_to_test_pypi:
        description: 'Publish to TestPyPI or not'
        type: boolean
        required: true

# https://cibuildwheel.pypa.io/en/stable/ci-services/#github-actions
jobs:
  make_sdist:
    name: Build sdist
    runs-on: ubuntu-24.04  # It's installed with Python 3.12.3
    steps:
      - uses: actions/checkout@v5

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-15-intel is an Intel runner, macos-14 is Apple silicon
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-14]

    steps:
      - uses: actions/checkout@v5

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  evaluate_variables:
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.evaluate.outputs.should_publish }}
      is_tagged: ${{ steps.evaluate.outputs.is_tagged }}
    steps:
      - id: evaluate
        run: |
          is_tagged_release="${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}"
          is_manual_release="${{ github.event_name == 'workflow_dispatch' && inputs.publish_to_test_pypi == 'true' }}"
          
          echo "Current event: ${{ github.event_name }}"
          echo "Is Tagged: $is_tagged_release"
          echo "Is Manual: $is_manual_release"

          echo "is_tagged_release=$is_tagged_release" >> "$GITHUB_OUTPUT"
          echo "is_manual_release=$is_manual_release" >> "$GITHUB_OUTPUT"
          if [[ "$is_tagged_release" == "true" || "$is_manual_release" == "true" ]]; then
            echo "should_publish=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_publish=false" >> "$GITHUB_OUTPUT"
          fi

  pypi_upload:
    needs: [build_wheels, make_sdist, evaluate_variables]

    # https://docs.pypi.org/trusted-publishers/using-a-publisher/
    environment: pypi_release
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    if: ${{ needs.evaluate_variables.outputs.should_publish == 'true' }}
    steps:
    - uses: actions/download-artifact@v5
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        # https://github.com/pypa/gh-action-pypi-publish/issues/283
        attestations: false

    - name: Publish distribution to PyPI
      if: ${{ needs.evaluate_variables.outputs.is_tagged_release == 'true' }}
      uses: pypa/gh-action-pypi-publish@release/v1
