name: CI workflow for PyFastCDC

on:
  push:
    paths:
      - '.github/workflows/package.yml'
      - '.github/workflows/build.yml'
      - '.github/workflows/test.yml'
      - 'pyfastcdc/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'MANIFEST.in'
  pull_request:
  workflow_dispatch:
    inputs:
      publish_to_test_pypi:
        description: 'Publish to TestPyPI or not'
        type: boolean
        required: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml

  evaluate:
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.evaluate.outputs.should_publish }}
      is_tagged: ${{ steps.evaluate.outputs.is_tagged }}
    steps:
      - id: evaluate
        run: |
          is_tagged_release="${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}"
          is_manual_release="${{ github.event_name == 'workflow_dispatch' && inputs.publish_to_test_pypi == 'true' }}"

          echo "Current event: ${{ github.event_name }}"
          echo "Is Tagged: $is_tagged_release"
          echo "Is Manual: $is_manual_release"

          echo "is_tagged_release=$is_tagged_release" >> "$GITHUB_OUTPUT"
          echo "is_manual_release=$is_manual_release" >> "$GITHUB_OUTPUT"
          if [[ "$is_tagged_release" == "true" || "$is_manual_release" == "true" ]]; then
            echo "should_publish=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_publish=false" >> "$GITHUB_OUTPUT"
          fi

  pypi_upload:
    name: Publish package to (Test)PyPI
    needs: [ test, build, evaluate ]

    # https://docs.pypi.org/trusted-publishers/using-a-publisher/
    environment: pypi_release
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    if: ${{ needs.evaluate.outputs.should_publish == 'true' }}
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          # https://github.com/pypa/gh-action-pypi-publish/issues/283
          attestations: false

      - name: Publish distribution to PyPI
        if: ${{ needs.evaluate.outputs.is_tagged_release == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
